spring.application.name=pizzeria-web

server.port=${WEB_PORT:8080}

spring.thymeleaf.cache=false

com.resto.pizzeria.web.apiUrl=${API_URL:http://localhost:8090/api}
com.resto.pizzeria.web.baseUrl=${WEB_URL:http://localhost:8080}
